// lib/theme/app_theme.dart — the app's single Material 3 ThemeData.
//
// REL-02 (Phase 6): tuned, not replaced. The Colors.teal seed is preserved
// exactly — every prior phase's UAT'd accent usage (the home FAB, every
// sheet's [ Lưu ], onboarding's progress bar, the Garage FAB) resolves
// through colorScheme.primary from this exact seed, so swapping it would
// be a far larger blast radius than this phase asks for
// (06-UI-SPEC.md § Design System). The only change this phase makes is an
// explicit `brightness: Brightness.light` — Material's own current default
// made explicit, not a behavior change. No `themeMode`, no dark variant:
// no requirement in this milestone asks for dark mode, and adding one now
// would be exactly the scope creep D-34 exists to catch.
//
// The 1024x1024 opaque launcher icon and splash (also REL-02) are
// generated by tool/generate_icon_test.dart and wired via the
// flutter_launcher_icons / flutter_native_splash config blocks in
// pubspec.yaml — see those files, not this one, for the icon/splash
// pipeline.
import 'package:flutter/material.dart';

final ThemeData appTheme = ThemeData(
  useMaterial3: true,
  colorScheme: ColorScheme.fromSeed(seedColor: Colors.teal),
  brightness: Brightness.light,
);
